AWS:
  Region Name: us-west-2
  Datalake Name: oedi-data-lake
  Databases:
    - Identifier: pv_rooftops
      Name: oedi_pv_rooftops
      Locations:
        - s3://oedi-data-lake/pv-rooftop/aspects/
        - s3://oedi-data-lake/pv-rooftop/buildings/
        - s3://oedi-data-lake/pv-rooftop/developable-planes/
        - s3://oedi-data-lake/pv-rooftop/rasd/
        - s3://oedi-data-lake/pv-rooftop-pr/developable-planes/
    - Identifier: buildstock
      Name: oedi_buildstock
      Locations:
        - s3://oedi-data-lake/nrel-pds-building-stock/end-use-load-profiles-for-us-building-stock/2021/comstock_amy2018_release_1/
        - s3://oedi-data-lake/nrel-pds-building-stock/end-use-load-profiles-for-us-building-stock/2021/comstock_tmy3_release_1/
        - s3://oedi-data-lake/nrel-pds-building-stock/end-use-load-profiles-for-us-building-stock/2021/resstock_amy2018_release_1/
        - s3://oedi-data-lake/nrel-pds-building-stock/end-use-load-profiles-for-us-building-stock/2021/resstock_tmy3_release_1/
    - Identifier: tracking_the_sun
      Name: oedi_tracking_the_sun
      Locations:
        - s3://oedi-data-lake/tracking-the-sun/2018/
        - s3://oedi-data-lake/tracking-the-sun/2019/
        - s3://oedi-data-lake/tracking-the-sun/2020/
        - s3://oedi-data-lake/tracking-the-sun/2021/
        - s3://oedi-data-lake/tracking-the-sun/2022/
        - s3://oedi-data-lake/tracking-the-sun/2023/
    - Identifier: atb
      Name: oedi_atb
      Locations:
        - s3://oedi-data-lake/ATB/electricity/parquet/2019/
        - s3://oedi-data-lake/ATB/electricity/parquet/2020/
        - s3://oedi-data-lake/ATB/electricity/parquet/2021/
        - s3://oedi-data-lake/ATB/electricity/parquet/2022/
        - s3://oedi-data-lake/ATB/electricity/parquet/2023/
    - Identifier: pvdaq
      Name: oedi_pvdaq
      Locations:
        - s3://oedi-data-lake/pvdaq/parquet/site/
        - s3://oedi-data-lake/pvdaq/parquet/system/
        - s3://oedi-data-lake/pvdaq/parquet/inverters/
        - s3://oedi-data-lake/pvdaq/parquet/meters/
        - s3://oedi-data-lake/pvdaq/parquet/metrics/
        - s3://oedi-data-lake/pvdaq/parquet/modules/
        - s3://oedi-data-lake/pvdaq/parquet/mount/
        - s3://oedi-data-lake/pvdaq/parquet/other-instruments/
        - s3://oedi-data-lake/pvdaq/parquet/pvdata/
    - Identifier: nso
      Name: oedi_nso
      Locations:
        - s3://oedi-data-lake-rawdata/NSO-2/inflow_mast_1min/
        - s3://oedi-data-lake-rawdata/NSO-2/inflow_mast_20Hz/
        - s3://oedi-data-lake-rawdata/NSO-2/lidar/
        - s3://oedi-data-lake-rawdata/NSO-2/loads_1min/
        - s3://oedi-data-lake-rawdata/NSO-2/loads_20Hz/
        - s3://oedi-data-lake-rawdata/NSO-2/wake_masts_1min/
        - s3://oedi-data-lake-rawdata/NSO-2/wake_masts_20Hz/

  Staging Location: s3://user-owned-staging-bucket/
  Tags:
    - Key: Project
      Value: OEDI
    - Key: Release
      Value: 0.2.3
